services:
  api:
    image: kacperhemperek/tw-api:latest
    ports:
      - 1337:1337
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_URL=${DB_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}

  web:
    image: kacperhemperek/tw-web:latest
    ports:
      - 2137:80

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=${DB_USERNAME}/${DB_PASSWORD} # Set default username/password
    ports:
      # Only expose the bold to not enable connecting to database borwser
      - "7687:7687" # Expose Bolt port for external connections if needed
    volumes:
      - tw_db_data:/data
      - tw_db_logs:/logs

volumes:
  tw_db_data:
  tw_db_logs:
