name: Deploy Application To Hetzner VPS

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  push_api_to_registry:
    name: Build and push api container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup Builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: ./api/
          file: ./api/Dockerfile
          push: true
          tags: kacperhemperek/tw-api:latest
          cache-from: type=inline,ref=kacperhemperek/tw-api:latest
          cache-to: type=inline

  push_frontend_to_registry:
    name: Build and push frontend container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: ./web/
          file: ./web/Dockerfile
          push: true
          tags: kacperhemperek/tw-web:latest
          cache-from: type=inline,ref=kacperhemperek/tw-web:latest
          cache-to: type=inline

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    needs: [push_frontend_to_registry, push_api_to_registry]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          port: 22
          script: |
            cd twitter-v2
            git pull
            cd deploy
            bash ./deploy.sh
